---
title: "build_simulation"
output: html_document
date: "2023-04-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
source('fns.r')
```
```{r}




```

```{r}
source('fns.R')
```


```{r}

## stockpiles

drawpoint_stocks_max = 9999999
stope_stocks_max =1000
hoist_stocks_max = 9999999

#unit sizes
cave_notional_size=1000
bogger_bucket_size =7
truck_load_size=70
hoist_nominal_size =1000

#unit rates and reliability
# Bogger
n_boggers <- 2
bogger_get_delay <- 50
bogger_haul_loaded_delay <- 90
bogger_dump_delay <- 20
bogger_haul_empty_delay=75
bogger_mttr_str = 'function() max(1, rnorm(1, 3600, 360))'
bogger_mtbf_str = 'function() max(1, rexp(1, rate = 1/(24*3600)))'

# Truck
n_trucks <- 2
truck_get_delay <- 120
truck_haul_loaded_delay <- 1200
truck_dump_delay <- 20
truck_haul_empty_delay=1100
truck_mttr_str = 'function() max(1, rnorm(1, 3600, 360))'
truck_mtbf_str = 'function() max(1, rexp(1, rate = 1/(24*3600)))'


```


```{r}
n_boggers <- 2
n_trucks <- 2

pilenames=c('drawpoint','stope_stock','hoist_stock')
maxstocks=c(drawpoint_stocks_max,stope_stocks_max,hoist_stocks_max) 
initstocks=c(drawpoint_stocks_max,stope_stocks_max/2,0)
access_limit=c(3,2,1) # number of activities that can operate on pile at any one time



mod_df <- init_model(model='model',level = 1)

# build bogger trajectory

mod_df <- build_stockpiles(mod_df,pilenames=pilenames,maxstocks=maxstocks,initstocks=initstocks,access_limit)
mod_df <- add_trajectory_to_model(
  modelname = 'newmodel',
  item='bogger',
  modeldf = mod_df,
  n_items = n_boggers,
  item_unit_capacity = bogger_bucket_size,
  item_mttr = bogger_mttr_str,
  item_mtbf = bogger_mtbf_str
)
mod_df <- add_lhd (
  modelname = 'model',
  mod_df = mod_df,
  item = 'bogger',
  activity = 'lhd',
  # Get Vars
  get_resources=n_boggers,
  get_delay=bogger_get_delay,
  get_stockpile='drawpoint',
  get_secondary_unit_name='cave',
  get_secondary_unit_capacity=cave_notional_size,
  # haul loaded Vars
  haul_loaded_resources=n_boggers,
  haul_loaded_delay=bogger_haul_loaded_delay,
  # put vars
  put_resources=n_boggers,
  put_delay=bogger_dump_delay,
  put_stockpile='stope_stock',
  put_secondary_unit_name='truck',
  put_secondary_unit_capacity=truck_load_size,
  
  # haul empty
  haul_empty_resources = n_boggers,
  haul_empty_delay = bogger_haul_empty_delay,
  trj_step = -1
)

mod_df <- create_close_trj('model',mod_df,'bogger')

## Build truck trajectory

mod_df <- add_trajectory_to_model(
  modelname = 'newmodel',
  item='truck',
  modeldf = mod_df,
  n_items = n_trucks,
  item_unit_capacity = truck_load_size,
  item_mttr =  truck_mttr_str,
  item_mtbf = truck_mtbf_str
)
mod_df <- add_lhd (
  modelname = 'model',
  mod_df = mod_df,
  item = 'truck',
  activity = 'truck_haul',
  # Get Vars
  get_resources=1, #only one loader at stockpile
  get_delay=truck_get_delay,
  get_stockpile='stope_stock',
  get_secondary_unit_name='bogger',
  get_secondary_unit_capacity=bogger_bucket_size,
  # haul loaded Vars
  haul_loaded_resources=n_trucks,
  haul_loaded_delay=truck_haul_loaded_delay,
  # put vars
  put_resources=1,# single tip point
  put_delay=truck_dump_delay,
  put_stockpile='hoist_stock',
  put_secondary_unit_name='hoist',
  put_secondary_unit_capacity=hoist_nominal_size,
  
  # haul empty
  haul_empty_resources = n_trucks,# all trucks can be hauling at the same time
  haul_empty_delay = truck_haul_empty_delay,
  trj_step = -1
)

mod_df <- create_close_trj('model',mod_df,'truck')



code <- join_code(mod_df)

save_text_to_file(code, '_nmod_df.r')
#file.show('_nmod_df.r')
source('_nmod_df.r')
sink(file='./code.log.txt')
env <- env %>% run(7*24*360)
sink()


```
```{r}
#get basic data 
resourcemon <- get_mon_resources(env) 
arrivemon <- get_mon_arrivals(env, per_resource = T) %>% 
  mutate(wait_time=end_time-start_time-activity_time)


log <- read.delim('code.log.txt',sep=":",col.names=c('time','item','item_type','activity','record')) %>%
  mutate(time=as.numeric(time)
         
         
atts <- get_mon_attributes(env) 

stocks <- atts %>% 
  filter(key %like% 'stocks_val')

stocks %>% ggplot(aes(x=time,y=value,colour=key))+
  geom_point()+
  lims(y=c(0,stope_stocks_max))
,
         hrs=time/3600)
```

```{r}

```

